Make `WebSocketServer#handleUpgrade()` callback optional
websockets/ws pull request #1968
Opened 2021-11-02 11:44 UTC by lpinca

If the upgrade is successful and the `callback` argument is not
provided, then emit the `'connection'` event.

Refs: https://github.com/websockets/ws/pull/1966

2021-11-02 11:51 UTC, lpinca commented
I don't like this because the method behavior depends on the `callback` argument. Instead it should always or never emit the `'connection'` event, regardless of whether the `callback` argument is given or not.

2021-11-02 12:35 UTC, sdrsdr commented
Works for me! 😃

2021-11-02 13:20 UTC, sdrsdr commented
https://github.com/websockets/ws/blob/5b87c5191ddbdae974f553fa841270b7919ae10c/test/handleupgrade-default-cb.test.js this is a test case I've forgotten in my firts commit in my PR. You can use it to test your implementation also

2021-11-02 13:25 UTC, lpinca commented
> https://github.com/websockets/ws/blob/5b87c5191ddbdae974f553fa841270b7919ae10c/test/handleupgrade-default-cb.test.js this is a test case I've forgotten in my firts commit in my PR. You can use it to test your implementation also 

It's already covered by this change https://github.com/websockets/ws/blob/bc73223c3e0ec7ac503ef59ccb4d44479f5b4b8a/lib/websocket-server.js#L108. A lot of existing test would fail if the `'connection'` event is not emitted.

2021-11-02 15:06 UTC, lpinca commented
I will keep this open for a while to collect feedback. If no one will comment I will close it.

2021-11-02 15:42 UTC, sdrsdr commented
If you publish new package version I can try update the TypeScript definitions at DefinitelyTyped

2021-11-11 12:04 UTC, sdrsdr commented
What is the timeframe for this PR?

2021-11-11 12:05 UTC, lpinca commented
See https://github.com/websockets/ws/pull/1968#issuecomment-957777758.

2021-11-12 08:11 UTC, KVROHITH098 requested changes
I approve But I want this to be validated.

2021-11-16 19:09 UTC, lpinca commented
I'm closing this as per https://github.com/websockets/ws/pull/1968#issuecomment-957777758.

2021-11-16 19:09 UTC, closed without merging

2021-11-16 21:01 UTC, sdrsdr commented
Closed but not merged? I'm not sure what's going on here!

2021-11-17 06:40 UTC, lpinca commented
Yes, aside from yours, there seems to be no interest in getting this merged.